---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: raquel
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: registry.deti:5000/app_raquel:v2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: raquel
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app

