apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raquel-app-pvc
  namespace: raquel 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
